version: '3.8'

services:
  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: city-assistant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - city-assistant-backend
    restart: unless-stopped
    networks:
      - city-assistant-network

  # Backend Service with Replicas
  city-assistant-backend:
    build: ./city-assistant-backend
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./city-assistant-backend/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - city-assistant-network
    deploy:
      replicas: 3

  # Development version with hot reload
  city-assistant-dev:
    build: ./city-assistant-backend
    container_name: city-assistant-dev
    ports:
      - "8001:8000"
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    volumes:
      - ./city-assistant-backend:/app
      - ./city-assistant-backend/logs:/app/logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    networks:
      - city-assistant-network
    profiles:
      - dev

networks:
  city-assistant-network:
    driver: bridge
