version: '3.8'

services:
  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: city-assistant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - city-assistant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: city-assistant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - city-assistant-backend
      - redis
    restart: unless-stopped
    networks:
      - city-assistant-network

  # Backend Service with Replicas
  city-assistant-backend:
    build: ./city-assistant-backend
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./city-assistant-backend/logs:/app/logs
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - city-assistant-network
    deploy:
      replicas: 3

  # Development version with hot reload
  city-assistant-dev:
    build: ./city-assistant-backend
    container_name: city-assistant-dev
    ports:
      - "8001:8000"
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./city-assistant-backend:/app
      - ./city-assistant-backend/logs:/app/logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - city-assistant-network
    profiles:
      - dev

networks:
  city-assistant-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
